### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку mutex Маркелов

### ISSUE THREAD

**Issue by darkpeaceduck** [darkpeaceduck/au-linux-kernel-autumn-2016#5]
https://github.com/darkpeaceduck/au-linux-kernel-autumn-2016/commit/e4de9407e1243f641d2f232fcd82e138b7ce381a

**Comment by darkpeaceduck** [comment]
Пофикшен
https://github.com/darkpeaceduck/au-linux-kernel-autumn-2016/commit/9fc49616fb8b73acf2c54f63998352b934578cea

**Comment by eabatalov** [comment]
Неплохо.
Реф каунтинг, как мы обсуждали, можно было бы не делать.
Используй atomic операции для простых действий типа реф каунтинга и сравнения с нулем.
80% за задание.
